{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "portscan.serviceAccountName" . }}
  labels:
    {{- include "portscan.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: default
  name: portscan-list-nodes
rules:
- apiGroups: [""] 
  resources: 
    - pods
    - nodes
    - namespaces
  verbs: 
    - get
    - watch
    - list
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: portscan-list-nodes-role-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: {{ include "portscan.serviceAccountName" . }}
    namespace: default
roleRef:
  kind: ClusterRole
  name: portscan-list-nodes
  apiGroup: rbac.authorization.k8s.io
